"use strict";
const { resolveTransition, TERMINAL } = require("./preorderTransitions");
function fail(statusCode,message,extra={}){throw Object.assign(new Error(message),{statusCode,...extra});}
function positive(value,label){const number=Number(value);if(!Number.isFinite(number)||number<=0)fail(400,`${label} ต้องมากกว่า 0`);return number;}
function expectedVersion(body){const value=Number(body?.expectedVersion);if(!Number.isInteger(value)||value<1)fail(400,"expectedVersion ไม่ถูกต้อง");return value;}
function requireRole(auth,...roles){if(!roles.includes(auth?.role))fail(403,"Forbidden");}
async function lockedCase(client,auth,publicId){const params=[publicId];let scope="";if(auth.role!=="admin"){if(auth.role!=="staff"||!auth.effectiveBranchCode)fail(403,"Forbidden");params.push(auth.effectiveBranchCode);scope=" AND branch_code=$2";}const result=await client.query(`SELECT * FROM customer_relations.preorder_cases WHERE public_id=$1${scope} FOR UPDATE`,params);if(!result.rows[0])fail(404,"Not found");return result.rows[0];}
async function nextSeq(client,caseId){const result=await client.query("SELECT GREATEST(COALESCE((SELECT MAX(activity_seq) FROM customer_relations.preorder_events WHERE case_id=$1),0),COALESCE((SELECT MAX(activity_seq) FROM customer_relations.preorder_messages WHERE case_id=$1),0))+1 AS seq",[caseId]);return Number(result.rows[0]?.seq||1);}
function createPreorderWorkflow({db}){
 async function mutate(auth,publicId,body,{action,eventType,roles,sideEffect,payload=()=>({}),noteRequired=false}){requireRole(auth,...roles);const version=expectedVersion(body);if(noteRequired&&!String(body.note||body.reason||"").trim())fail(400,"กรุณาระบุเหตุผล");const client=await db.connect();try{await client.query("BEGIN");const row=await lockedCase(client,auth,publicId);if(Number(row.version)!==version)fail(409,"ข้อมูลถูกแก้ไขแล้ว กรุณาโหลดใหม่",{code:"VERSION_CONFLICT",current:{publicId:row.public_id,status:row.status,version:row.version}});const toStatus=resolveTransition({status:row.status,action,role:auth.role,priorStatus:row.prior_status});if(!toStatus)fail(409,"ไม่สามารถทำรายการนี้ในสถานะปัจจุบัน",{code:"INVALID_TRANSITION",current:{publicId:row.public_id,status:row.status,version:row.version}});const seq=await nextSeq(client,row.case_id);if(sideEffect)await sideEffect(client,row,seq);const terminal=TERMINAL.has(toStatus);const update=await client.query(`UPDATE customer_relations.preorder_cases SET status=$2,prior_status=CASE WHEN $3='request_info' THEN status WHEN $4 THEN status ELSE prior_status END,assigned_admin_user=CASE WHEN $3='start_review' THEN $5 ELSE assigned_admin_user END,version=version+1,last_activity_at=now(),updated_at=now(),closed_at=CASE WHEN $4 THEN now() ELSE NULL END,closed_by=CASE WHEN $4 THEN $5 ELSE NULL END WHERE case_id=$1 RETURNING *`,[row.case_id,toStatus,action,terminal,auth.userId]);await client.query("INSERT INTO customer_relations.preorder_events(case_id,activity_seq,event_type,actor_user_id,actor_role,from_status,to_status,payload_json) VALUES($1,$2,$3,$4,$5,$6,$7,$8::jsonb)",[row.case_id,seq,eventType,auth.userId,auth.role,row.status,toStatus,JSON.stringify(payload(row))]);const recipient=auth.role==="admin"?"staff":"admin";await client.query("INSERT INTO customer_relations.preorder_notifications(case_id,recipient_role,recipient_branch_code,activity_seq,notification_type) VALUES($1,$2,$3,$4,$5)",[row.case_id,recipient,recipient==="staff"?row.branch_code:null,seq,eventType]);await client.query("COMMIT");return update.rows[0];}catch(error){try{await client.query("ROLLBACK");}catch{}throw error;}finally{client.release();}}
 const simple=(action,eventType,roles,options={})=>(auth,id,body)=>mutate(auth,id,body,{action,eventType,roles,...options});
 async function publishQuote(auth,id,body){const lines=Array.isArray(body.lines)?body.lines:[];if(!lines.length)fail(400,"กรุณาระบุราคาอย่างน้อย 1 รายการ");return mutate(auth,id,body,{action:"publish_quote",eventType:"QUOTE_PUBLISHED",roles:["admin"],sideEffect:async(client,row)=>{const items=await client.query("SELECT item_id FROM customer_relations.preorder_items WHERE case_id=$1",[row.case_id]);const allowed=new Set(items.rows.map(x=>Number(x.item_id)));const seen=new Set();for(const line of lines){const itemId=Number(line.itemId);if(!allowed.has(itemId)||seen.has(itemId))fail(400,"รายการเสนอราคาไม่ถูกต้อง");seen.add(itemId);positive(line.offeredQty,"จำนวนเสนอ");const price=Number(line.unitPrice);if(!Number.isFinite(price)||price<0)fail(400,"ราคาต้องไม่ติดลบ");}const last=await client.query("SELECT quote_id,quote_version FROM customer_relations.preorder_quotes WHERE case_id=$1 ORDER BY quote_version DESC LIMIT 1",[row.case_id]);const quote=await client.query("INSERT INTO customer_relations.preorder_quotes(case_id,quote_version,valid_until,public_note,admin_internal_note,published_by,supersedes_quote_id) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING quote_id",[row.case_id,Number(last.rows[0]?.quote_version||0)+1,body.validUntil||null,String(body.note||"").trim()||null,String(body.internalNote||"").trim()||null,auth.userId,last.rows[0]?.quote_id||null]);for(const line of lines)await client.query("INSERT INTO customer_relations.preorder_quote_lines(quote_id,item_id,offered_qty,unit_price,unit) VALUES($1,$2,$3,$4,$5)",[quote.rows[0].quote_id,Number(line.itemId),Number(line.offeredQty),Number(line.unitPrice),String(line.unit||"").trim()||null]);},payload:()=>({lineCount:lines.length})});}
 async function customerDecision(auth,id,body){const decision=body.decision==="DECLINED"?"DECLINED":"ACCEPTED";const action=decision==="ACCEPTED"?"accept":"decline";const lines=Array.isArray(body.lines)?body.lines:[];if(decision==="ACCEPTED"&&!lines.length)fail(400,"กรุณาระบุจำนวนที่ลูกค้ายืนยัน");return mutate(auth,id,body,{action,eventType:decision==="ACCEPTED"?"CUSTOMER_ACCEPTED":"CUSTOMER_DECLINED",roles:["staff"],sideEffect:async(client,row)=>{const quote=await client.query("SELECT quote_id FROM customer_relations.preorder_quotes WHERE case_id=$1 ORDER BY quote_version DESC LIMIT 1",[row.case_id]);if(!quote.rows[0])fail(409,"ไม่พบใบเสนอราคาที่เผยแพร่");const result=await client.query("INSERT INTO customer_relations.preorder_customer_decisions(case_id,quote_id,decision,reason,recorded_by) VALUES($1,$2,$3,$4,$5) RETURNING decision_id",[row.case_id,quote.rows[0].quote_id,decision,String(body.reason||"").trim()||null,auth.userId]);if(decision==="ACCEPTED"){const items=await client.query("SELECT item_id FROM customer_relations.preorder_items WHERE case_id=$1",[row.case_id]);const allowed=new Set(items.rows.map(x=>Number(x.item_id)));const seen=new Set();for(const line of lines){const itemId=Number(line.itemId);if(!allowed.has(itemId)||seen.has(itemId))fail(400,"จำนวนยืนยันไม่ถูกต้อง");seen.add(itemId);const qty=positive(line.finalQty,"จำนวนยืนยัน");await client.query("INSERT INTO customer_relations.preorder_decision_lines(decision_id,item_id,final_qty) VALUES($1,$2,$3)",[result.rows[0].decision_id,itemId,qty]);await client.query("UPDATE customer_relations.preorder_items SET confirmed_qty=$2 WHERE item_id=$1",[itemId,qty]);}}},payload:()=>({decision})});}
 async function unavailable(auth,id,body){const reason=String(body.reasonCode||"");return mutate(auth,id,body,{action:"unavailable",eventType:"MARKED_UNAVAILABLE",roles:["admin"],sideEffect:async(client,row)=>{const valid=await client.query("SELECT requires_note FROM customer_relations.preorder_unavailable_reasons WHERE reason_code=$1 AND is_active=TRUE",[reason]);if(!valid.rows[0])fail(400,"เหตุผลไม่ถูกต้อง");if(valid.rows[0].requires_note&&!String(body.note||"").trim())fail(400,"กรุณาระบุรายละเอียดเพิ่มเติม");await client.query("UPDATE customer_relations.preorder_cases SET close_reason_code=$2,close_note=$3 WHERE case_id=$1",[row.case_id,reason,String(body.note||"").trim()||null]);await client.query("INSERT INTO customer_relations.preorder_procurement_outcomes(case_id,outcome_type,public_note,admin_internal_note,reason_code,recorded_by) VALUES($1,'UNAVAILABLE',$2,$3,$4,$5)",[row.case_id,String(body.note||"").trim()||null,String(body.internalNote||"").trim()||null,reason,auth.userId]);},payload:()=>({reasonCode:reason})});}
 async function matchSku(auth,id,itemId,body){requireRole(auth,"admin");const version=expectedVersion(body);const client=await db.connect();try{await client.query("BEGIN");const row=await lockedCase(client,auth,id);if(Number(row.version)!==version)fail(409,"ข้อมูลถูกแก้ไขแล้ว กรุณาโหลดใหม่",{code:"VERSION_CONFLICT",current:{status:row.status,version:row.version}});const sku=await client.query("SELECT sku_id FROM public.skus WHERE sku_id=$1",[Number(body.skuId)]);if(!sku.rows[0])fail(400,"ไม่พบสินค้าในระบบ");const changed=await client.query("UPDATE customer_relations.preorder_items SET matched_sku_id=$3,matched_by=$4,matched_at=now() WHERE case_id=$1 AND item_id=$2 AND item_kind='FREEFORM' RETURNING item_id",[row.case_id,Number(itemId),Number(body.skuId),auth.userId]);if(!changed.rows[0])fail(404,"Not found");const seq=await nextSeq(client,row.case_id);await client.query("UPDATE customer_relations.preorder_cases SET version=version+1,last_activity_at=now(),updated_at=now() WHERE case_id=$1",[row.case_id]);await client.query("INSERT INTO customer_relations.preorder_events(case_id,activity_seq,event_type,actor_user_id,actor_role,payload_json) VALUES($1,$2,'ITEM_MATCHED',$3,'admin',$4::jsonb)",[row.case_id,seq,auth.userId,JSON.stringify({itemId:Number(itemId),skuId:Number(body.skuId)})]);await client.query("COMMIT");return {ok:true};}catch(error){try{await client.query("ROLLBACK");}catch{}throw error;}finally{client.release();}}
 const requestInfo=(auth,id,body)=>mutate(auth,id,body,{action:"request_info",eventType:"INFO_REQUESTED",roles:["admin"],noteRequired:true,payload:()=>({note:String(body.note).trim()})});
 const markOrdered=(auth,id,body)=>mutate(auth,id,body,{action:"ordered",eventType:"MARKED_ORDERED",roles:["admin"],sideEffect:(client,row)=>client.query("INSERT INTO customer_relations.preorder_procurement_outcomes(case_id,outcome_type,supplier_reference,public_note,admin_internal_note,recorded_by) VALUES($1,'ORDERED',$2,$3,$4,$5)",[row.case_id,String(body.supplierReference||"").trim()||null,String(body.note||"").trim()||null,String(body.internalNote||"").trim()||null,auth.userId]),payload:()=>({hasSupplierReference:Boolean(String(body.supplierReference||"").trim()),note:String(body.note||"").trim()||null})});
 const cancel=(auth,id,body)=>mutate(auth,id,body,{action:"cancel",eventType:"CASE_CANCELLED",roles:["staff"],noteRequired:true,payload:()=>({note:String(body.note||body.reason).trim()})});
 const reopen=(auth,id,body)=>mutate(auth,id,body,{action:"reopen",eventType:"CASE_REOPENED",roles:["admin"],noteRequired:true,payload:()=>({note:String(body.note||body.reason).trim()})});
 return {startReview:simple("start_review","REVIEW_STARTED",["admin"]),requestInfo,provideInfo:simple("provide_info","INFO_PROVIDED",["staff"]),publishQuote,customerDecision,markOrdered,markUnavailable:unavailable,confirmArrival:simple("arrive","BRANCH_ARRIVAL_CONFIRMED",["admin","staff"]),customerNotified:simple("notify_customer","CUSTOMER_NOTIFIED",["staff"]),complete:simple("complete","CASE_COMPLETED",["admin","staff"]),cancel,reopen,matchSku};
}
module.exports={createPreorderWorkflow,expectedVersion,positive};
